/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RouteTreeImport } from './routes/routeTree'
import { Route as RootImport } from './routes/root'
import { Route as LoginImport } from './routes/login'
import { Route as VendaVendaImport } from './routes/venda/venda'
import { Route as SubCategoriasSubCategoriasImport } from './routes/sub-categorias/sub-categorias'
import { Route as ProdutosProdutosImport } from './routes/produtos/produtos'
import { Route as DashboardDashboardImport } from './routes/dashboard/dashboard'
import { Route as CategoriasCategoriasImport } from './routes/categorias/categorias'

// Create/Update Routes

const RouteTreeRoute = RouteTreeImport.update({
  path: '/routeTree',
  getParentRoute: () => rootRoute,
} as any)

const RootRoute = RootImport.update({
  path: '/root',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const VendaVendaRoute = VendaVendaImport.update({
  path: '/venda/venda',
  getParentRoute: () => rootRoute,
} as any)

const SubCategoriasSubCategoriasRoute = SubCategoriasSubCategoriasImport.update(
  {
    path: '/sub-categorias/sub-categorias',
    getParentRoute: () => rootRoute,
  } as any,
)

const ProdutosProdutosRoute = ProdutosProdutosImport.update({
  path: '/produtos/produtos',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CategoriasCategoriasRoute = CategoriasCategoriasImport.update({
  path: '/categorias/categorias',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/root': {
      preLoaderRoute: typeof RootImport
      parentRoute: typeof rootRoute
    }
    '/routeTree': {
      preLoaderRoute: typeof RouteTreeImport
      parentRoute: typeof rootRoute
    }
    '/categorias/categorias': {
      preLoaderRoute: typeof CategoriasCategoriasImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/dashboard': {
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/produtos/produtos': {
      preLoaderRoute: typeof ProdutosProdutosImport
      parentRoute: typeof rootRoute
    }
    '/sub-categorias/sub-categorias': {
      preLoaderRoute: typeof SubCategoriasSubCategoriasImport
      parentRoute: typeof rootRoute
    }
    '/venda/venda': {
      preLoaderRoute: typeof VendaVendaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LoginRoute,
  RootRoute,
  RouteTreeRoute,
  CategoriasCategoriasRoute,
  DashboardDashboardRoute,
  ProdutosProdutosRoute,
  SubCategoriasSubCategoriasRoute,
  VendaVendaRoute,
])

/* prettier-ignore-end */
